-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Feb 24, 2024 at 07:19 AM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.0.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `merchandise`
--

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE `products` (
  `Id` int(5) NOT NULL,
  `Name` varchar(50) NOT NULL,
  `Category` varchar(25) NOT NULL,
  `Price` varchar(20) NOT NULL,
  `image` varchar(75) NOT NULL,
  `Description_1` varchar(1200) DEFAULT NULL,
  `Description_2` varchar(1200) DEFAULT NULL,
  `Description_3` varchar(1200) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`Id`, `Name`, `Category`, `Price`, `image`, `Description_1`, `Description_2`, `Description_3`) VALUES
(1, 'Gold Necklace Small with a Pendal ', 'Necklace', 'Rs 1299', 'images/banner img3.jpeg', 'It is a small and thin gold platted necklace with a small pendal.', 'It is light weight and easy to carry good for normal parties and functions.', 'The weight of this necklace is 20 grams and it is a non pure gold necklace and the weight of the pendal is 13 grams and '),
(2, 'Rose Gold Drop Wreath Necklace With Link Chain', 'Necklace', 'Rs 1499', 'images/necklace2.jpeg', 'The Rose Gold Pink Drop Wreath Necklace With Link Chain is inspired by the most special moments of life that make it all worth it.', 'The Rose Gold Pink Drop Wreath Necklace With Link Chain is handcrafted with love, just for YOU.<br>\r\nThese intricately made studs possess all the thoughtfulness you need around you.<br>\r\nWith the perfect balance of leaves, flowers, and drop design, this pendant is nothing less than a true masterpiece.', 'Take it along for those special, close-to-heart moments.<br><br>\r\n\r\nIncludes 16\" + 2\" adjustable Rose Gold Chain.<br>\r\nDimensions - 21mm X 15mm.<br>\r\nSterling Silver with Rose Gold plating and 925.<br> \r\nAAA+ Quality Zircons.\r\n'),
(3, 'Silver Solitaire Heart Necklace with Link Chain', 'Necklace', 'Rs 1599', 'images/necklace3.jpeg', 'No beauty shines brighter than a good heart and nothing complements your shine like this Silver Solitaire Heart Necklace.<br>\r\nBeauty with grace now, just like you!', ' Dimensions:16mm* 8mm AAA+ Heart-cut Zircon.<br>\r\n38cm+5cm Silver Chain. <br>\r\nSterling Silver with 925. <br> \r\nAnti-tarnish coating.', NULL),
(4, 'Rose Gold Solitaire Heart Necklace', 'Necklace', 'Rs 1599', 'images/necklace4.jpeg', 'The Rose Gold Solitaire Heart Necklace is inspired by the earnest call of love from your heart!', 'The Rose Gold Solitaire Heart Necklace has a lovely heart-shaped zircon in its design.', 'Includes 16\" + 2\" adjustable Rose Gold Chain. <br>\r\n925 Silver with Rose Gold plating. <br> \r\nAAA+ Quality Zircons. <br> \r\nDimensions: 18.5 mm x 8.2 mm. '),
(5, 'Golden Delicate Pearl Necklace', 'Necklace', 'Rs 1899', 'images/necklace5.jpeg', 'The Golden Delicate Pearl Necklace is inspired by the purity of white pearls and how they calm you down.', 'The golden necklace has pearls placed at a distance from each other on the necklace.', '925 Silver with Gold Plating. <br>\r\nPerfect for sensitive skin. <br>\r\nThe necklace size is 44 cm and the adjustable chain is 5 cm. '),
(6, 'Silver Mystic Blue Leaf Necklace', 'Necklace', 'Rs 3299', 'images/necklace6.jpeg', 'DIVA, it’s time to bask in nature\'s glory!<br> Inspired by the adorable leaves that mesmerize all who witness them swaying, these Silver Mystic Blue Leaf Necklace is YOUR new companions.<br> Why mystic? Because of the unique pattern on the leaf, of course!', 'This Silver Mystic Blue Leaf Necklace is handcrafted with love, just for YOU!<br> With captivating prismatic patterns on a silver leaf body, this gorgeous pendant is sure to fascinate everyone around YOU!', 'Get YOUR daily dose of nature with this beautiful necklace.<br><br>\r\n\r\n925 Silver. <br> \r\nIncludes 39.3cm + 5cm adjustable Sterling. <br> Silver Chain. <br>\r\npendent size 30mm X 10mm. <br>\r\nRhodium e-coat to prevent tarnish. '),
(7, 'Oxidised Silver Moonstone Crescent Necklace with B', 'Necklace', 'Rs 1699', 'images/necklace7.jpeg', 'The Oxidised Silver Moonstone Crescent Necklace with Box Chain is inspired by the gorgeous reflections of dreams that the moon casts with its illuminating light. <br>\r\nOpt for a Pale pastel satin maxi dress and pair it up with this pendant.', 'The Oxidised Silver Moonstone Crescent Necklace with Box Chain has an elegant design where the crescent is sculpted with intricate details while the moon stone adds to the beauty.', 'Includes 16” + 2” adjustable Silver chain. <br>\r\n925 Silver.'),
(8, 'Silver Star Constellation Necklace', 'Necklace', 'Rs 1999', 'images/necklace8.jpeg', 'The Silver Star Constellation Necklace is inspired by the love story that comes true when you wish upon a falling star!', 'The Silver Star Constellation Necklace has a very elegant design with gorgeous stars strung together and studded with zircons!', '925 Silver. <br>\r\nLength of the necklace is 40 cm with 7 cm adjustable portion. <br>\r\nCharm: 0.5 cm x 0.5 cm.'),
(9, 'Stay Golden Necklace', 'Necklace', 'Rs 1399', 'images/necklace9.jpeg', 'The Stay Golden Necklace is inspired by the mix of life\'s journey we all go through. <br>\r\nLife is nothing but a slide into the good days from bad days and so on.', 'The Stay Golden Necklace carries an intricately placed line of zircons to complement all your outfits.', 'Includes 16\" + 2\" adjustable Gold Chain. <br>\r\n925 Silver with Gold plating. <br>\r\nAAA+ Quality Zircons. <br>\r\nDimensions: 24 mm x 9 mm. '),
(10, 'Golden Classic Heart Necklace with Link Chain', 'Necklace', 'Rs 1799', 'images/necklace10.jpeg', 'Simple is always best when it comes to YOUR every day.<br> A sleek update to a classic, this Golden Classic Heart Necklace was made to always accompany YOU. <br> Neither too loud, nor too gaudy, this is the necklace YOU never need to take off.', 'This Golden Classic Heart Necklace has been handcrafted with love, especially for YOU!<br> Crafted in solid silver with a perfect gold finish, this necklace is perfect for every look.', 'This necklace will never let YOU down!\r\n<br><br>\r\nIncludes 16\" + 2\" adjustable Rose Gold Chain. <br>\r\n925 Sterling Silver with Rose Gold plating.'),
(11, 'Rose Gold Sun Flower Necklace with Link Chain', 'Necklace', 'Rs 2199', 'images/necklace11.jpeg', 'Dear DIVA, we know you love flowers, so here\'s another one for the collection.<br> Inspired by sunflowers in all their glory, this Rose Gold Sunflower Necklace is here to fill YOUR day with light and joy.', 'This Rose Gold Sunflower Necklace is handcrafted with love, just for YOU! <br> Featuring a sparkling zircon centrepiece surrounded by adorable petals, this pendant is an instant mood fixer. The rose gold finish just makes it all the more beautiful.\r\n', 'Channel YOUR sunny vibes with this cheerful necklace!\r\n<br><br>\r\nIncludes 38cm + 5cm adjustable Rose Gold Chain.<br>\r\nSterling Silver with Rose Gold plating and 925.<br> \r\nAAA+ Quality Zircons.'),
(12, 'Silver Drizzle Drop Necklace with Link Chain', 'Necklace', 'Rs 1799', 'images/necklace12.jpeg', 'Like a light drizzle on a summer afternoon, YOU are a marvel of nature that leaves everyone spellbound.<br> But even a soothing drizzle feels better when it partners with a chilly breeze.<br> Presenting the Silver Drizzle Drop Necklace, the breeze to your drizzle.', 'This Silver Drizzle Drop Necklace is handcrafted with love, just for YOU. The simple yet chic pendant has the shiniest zircon ever, nestled comfortably in a circular silver frame. <br> The perfect partner for a peerless beauty.', 'Wear it once and YOU will never want to take it off, we promise.\r\n<br><br>\r\nIncludes 38cm + 5cm adjustable Sterling. <br> Silver Chain. <br>\r\n925 silver. <br> \r\nAAA+ Quality Zircons.\r\nRhodium e-coat to prevent tarnish '),
(13, 'Silver Falling Dew Necklace with Box Chain', 'Necklace', 'Rs 1599', 'images/necklace13.jpeg', 'Hey DIVA, we know you love your early mornings. We got you a partner to enjoy them with! <br> Inspired by the glistening morning dew nestled on fresh leaves, this Falling Dew Necklace is guaranteed to refresh your mind, body and soul, just like the mornings you love.', 'Includes 38cm + 5cm adjustable Sterling Silver Chain. <br>\r\nSterling Silver with 925. <br> \r\nAAA+ Quality Zircons. <br>\r\nRhodium e-coat to prevent tarnish.', NULL),
(14, 'Golden Crimson Heart Necklace with Link Chain', 'Necklace', 'Rs 1999', 'images/necklace14.jpeg', 'Hearts? Check. Sparkle? Check. Spotlight? Double Check! DIVA, we don’t need to say much.<br> This Golden Ruby Red Heart Necklace does its own talking. It has only one message for YOU – Love YOURSELF!', 'This Golden Crimson Heart Pendant is handcrafted with love, just for YOU! <br> A sparkling crimson heart rests on a lustrous gold frame. <br>This necklace has been crafted for a singular purpose – to act as a reminder that YOU deserve all the love this world has to offer.', 'This necklace wants YOU to love YOURSELF! Style it as YOU see fit.\r\n\r\nIncludes 16\" + 2\" adjustable Gold Chain. <br>\r\n925 Sterling Silver with Gold plating. <br>\r\nAAA+ Quality Zircons.'),
(15, 'Dual Tone Infinity Heart Necklace with Link Chain', 'Necklace', 'Rs 2199', 'images/necklace15.jpeg', 'DIVA, we are all looking for love that is eternal and infinite.<br> We are all looking for our forever. This Dual Tone Infinity Heart Necklace is our way of supporting YOUR forever love.', 'This Dual Tone Infinity Heart Necklace is handcrafted with love, just for YOU.<br> This pendant is simple and elegant, with a sparkling heart resting on a radiant rose gold infinity. Truly perfect!\r\n', 'Let this necklace accompany YOU in YOUR journey of love!\r\n<br><br>\r\nIncludes 35cm + 2cm adjustable Rose Gold Chain. <br>\r\n925 Sterling Silver and 18K Rose Gold plating. <br>\r\nAAA+ Quality Zircon Stones. <br>\r\nHypoallergenic - Perfect for sensitive skin. <br>\r\nRhodium e-coat to prevent tarnish.'),
(16, 'Golden Heart to Heart Necklace', 'Necklace', 'Rs 1899', 'images/necklace16.jpeg', 'The Golden Heart to Heart Necklace is inspired by the heart-to-heart conversations that are the perfect cherry on the top moment for a love story about to begin!\r\n', 'The Golden Heart to Heart Necklace has a design with 2 hearts - one studded with zircons and one with outer lining, along with some zircon stones on the farther end.', 'Includes 16\" + 2\" adjustable Sterling Silver Chain with Gold plating. <br>\r\n925 Silver with Gold plating. <br>\r\nAAA+ Quality Zircons. <br>  \r\nDimensions: 10.5 mm x 9 mm.'),
(17, 'Rose Gold Glinting Crown Ring', 'Ring', 'Rs 1599', 'images/ring1.jpeg', 'The Rose Gold Glinting Crown Ring is about regal supremacy vibing with a theme of vintage renaissance.', 'The Rose Gold Glinting Crown Ring takes the shape of a crown that was your true calling.<br> With intricate zircon detailing, the rose gold-hued charm, and its crafty design - it makes an impression that lasts!', 'AAA+ Quality Zircon Stones.<br>\r\n925 Sterling Silver with Rose Gold plating.<br> \r\nAdjustable size to ensure no fitting issues. <br>\r\nDimension: 16 mm + Adjustable.'),
(18, 'Golden Star Constellation Ring', 'Ring', 'Rs 999', 'images/ring2.jpeg', 'DIVA, YOU are a beauty from the heavens. An angel living amongst the stars, YOU descended to make our world a better place.<br> Inspired by YOUR old friends, the little celestials that light up our night sky, comes this Golden Star Constellation Ring.', 'This Golden Star Constellation Ring is handcrafted with love, especially for YOU. <br>With intricately arranged stars on a golden chain, this sparkling ring is reminiscent of YOUR favourite celestial body.\r\n', 'This ring is here to make YOU stand out! Wear them whenever YOU want that extra oomph.\r\n<br><br>\r\n925 Sterling Silver with Gold plating. <br>\r\nAdjustable size to ensure no fitting issues.<br>\r\nRing size 5.5 - 10 / 16mm - 19.8mm (adjustable).'),
(19, 'Silver Passionate Love Ring', 'Ring', 'Rs 999', 'images/ring3.jpeg', 'The Silver Passionate Love Ring is inspired by the sparks of love.', 'The Silver Ring has a heart-shaped zircon stone implanted at the centre with mini spikes on top.', '925 Silver.<br> \r\nAdjustable size to ensure no fitting issues.<br>\r\nDiameter: 18 mm + Adjustable.<br>\r\nRhodium finish to prevent tarnish.'),
(20, 'Golden Eternity Ring', 'Ring', 'Rs 1099', 'images/ring4.jpeg', 'The Golden Eternity Ring is here to give a curvy spin to the classy good old gemstone design.<br> The best upgrade is right here DIVAs.', 'The Golden Eternity Ring is handcrafted with love, just for YOU. The gold plated frame softly curves at the front and the gemstones add to the look.', 'Slay this plot twist every day.\r\n<br><br>\r\nAAA+ Quality Zircon Stones.<br>\r\n925 Sterling Silver with Gold plating.<br>\r\nAdjustable size to ensure no fitting issues.'),
(21, 'Golden Flower Girl Ring', 'Ring', 'Rs 1499', 'images/ring5.jpeg', 'The Golden Flower Girl Ring is inspired by the demure style of a girl that only gets accentuated with exquisite finery.\r\n', 'The Gold Plated Flower Girl Ring has a lovely floral design with studded zircons.', '925 Sterling Silver with Gold plating.<br> \r\nAdjustable size to ensure no fitting issues.<br>\r\nAAA+ Quality Zircons.<br>\r\nDiameter: 18mm + top Adjustable.<br>\r\nDimension: 12 x 7.5 mm. '),
(22, 'Silver Snowfall Ring', 'Ring', 'Rs 1099', 'images/ring6.jpeg', 'The Silver Snowfall Ring is inspired by how with every falling flake, a unique spark of interest falls from heaven.', 'The silver ring has a zircon in the centre designed like a snowflake.', '925 Silver. <br>\r\nAdjustable size to ensure no fitting issues.<br>\r\nRhodium finish to prevent tarnish.<br>\r\nAAA+ Quality Zircon.<br>\r\nDiameter: 1.8 cm. '),
(23, 'Silver Zircon Love Island Ring', 'Ring', 'Rs 999', 'images/ring7.jpeg', 'The Silver Zircon Love Island Ring is inspired by an imaginary island where love prevails and everyone is always happy.', 'The Silver Ring has a sleek rim with a zircon centrepiece.\r\n<br><br>\r\n925 Silver. <br> \r\nAAA+ Quality Zircons. <br>\r\nAdjustable size to ensure no fitting issues. <br>\r\nDiameter: 18 mm + Adjustable.<br>\r\nRhodium finish to prevent tarnish. ', NULL),
(24, 'Silver Cupid Arrow Ring', 'Ring', 'Rs 1199', 'images/ring8.jpeg', 'The Silver Cupid Arrow Ring is inspired by Cupid\'s impeccable aim, striking right at our hearts.', 'The Silver Ring has a small sharp curve and the rim is studded with zircons.\r\n<br><br>\r\n925 Silver.<br> \r\nAAA+ Quality Zircons.<br>\r\nAdjustable size to ensure no fitting issues.<br>\r\nDiameter: 1.8cm.<br>\r\nFixed size.<br>\r\nRhodium finish to prevent tarnish.', NULL),
(25, 'Silver Stereo Hearts Ring', 'Ring', 'Rs 1499', 'images/ring9.jpeg', 'The Silver Stereo Hearts Ring is inspired by a heart full of love they keep singing about, heard off vintage stereo!', 'The Silver Stereo Hearts Ring has a beautiful silver finish and a gorgeous zircon.', '925 Sterling Silver. <br>\r\nAdjustable size to ensure no fitting issues.<br>\r\nDimension: 5.5 mm x 4 mm.<br>\r\nDiameter: 16 mm+ Adjustable.<br> \r\nRhodium finish to prevent tarnish.'),
(26, 'Rose Gold Queen\'s Crown Ring', 'Ring', 'Rs 2199', 'images/ring10.jpeg', 'Queens are made to revel in love and glory, and DIVA, so are you.<br> We firmly believe this. We wanted to bring You a ring that would signify YOUR royalty, a crown YOU could always carry around.<br> This Rose Gold Queen’s Crown Ring is our answer.', 'This Rose Gold Queen’s Crown Ring has been handcrafted with love, especially for YOU!<br> A dazzling zircon crown on a rose gold body gives this ring a truly royal vibe.', 'Would a queen ever let go of her royal aura? We think not.\r\n<br><br>\r\nAAA+ Quality Zircon Stones.<br>\r\n925 Sterling Silver with Rose Gold plating.<br> \r\nAdjustable size to ensure no fitting issues.<br>\r\nHypoallergenic - Perfect for sensitive skin.<br>\r\nRing size 5.5 - 8 / 16mm - 18mm (adjustable).'),
(27, 'Silver Infinity Heart Ring', 'Ring', 'Rs 1699', 'images/ring11.jpeg', 'DIVA, we are all looking for love that is eternal and infinite.<br> We are all looking for our forever. <br>This Silver Infinity Heart Ring is our way of supporting YOUR forever love.', 'This Silver Infinity Heart Ring is handcrafted with love, just for YOU. <br>This ring is simple and elegant, with a sparkling heart on an infinity shaped zircon band. Truly perfect!', 'Let this ring accompany YOU in YOUR journey of love!\r\n<br><br>\r\nAAA+ Quality Zircon Stones.<br>\r\n925 Sterling Silver.<br>\r\nAdjustable size to ensure no fitting issues.<br>\r\nRing size 10.5-13/ 20.5mm -22.2mm (adjustable).<br>\r\nRhodium e-coat to prevent tarnish.'),
(28, 'Rose Gold Wreath Ring', 'Ring', 'Rs 1499', 'images/ring12.jpeg', 'True divinity is simply too scarce. All we can do is attempt to capture its essence.<br> Case in point, this Rose Gold Wreath Ring! A touch of the divine, a splash of shine, only for YOU!', 'This Rose Gold Wreath Ring is handcrafted with love, just for YOU!<br> A sparkling wreath is formed entirely out of sparkling zircon and rose gold leaves.<br> Each leaf is handcrafted with precision, lending these an unmatched beauty!', 'AAA+ Quality Zircon Stones.<br>\r\n925 Sterling Silver with Rose Gold plating.<br> \r\nFixed Size.<br>\r\nRing Size: Indian - 12; US - 6.<br>\r\nHypoallergenic - Perfect for sensitive skin.'),
(29, 'Silver Studded Rose Ring', 'Ring', 'Rs 1999', 'images/ring13.jpeg', 'Shakespeare once said, \"A rose by any other would smell just as sweet.\"<br> We agree! No matter what YOU are called, be it DIVA, superwoman, or any other name, YOU are the most special person in our hearts.<br> Inspired by YOUR uniqueness and charm, comes this Silver Studded Rose Ring.', 'This Silver Studded Rose Ring has been handcrafted with love, especially for YOU!<br> A delicate rose at one end, a sparkling zircon flower on the other, this ring represents the pinnacle of craftsmanship. Perfect for a beauty like YOU!\r\n', 'This ring wants to be by YOUR side, always. Let it, please?\r\n<br><br>\r\nAAA+ Quality Zircon Stones. <br>\r\n925 Sterling Silver. <br> \r\nAdjustable size to ensure no fitting issues.<br>\r\nRing size 5.5-10/ 16mm -19.8mm (adjustable).<br>\r\nRhodium e-coat to prevent tarnish. '),
(30, ' Rose Gold Solitaire Spin Ring', 'Ring', 'Rs 1999', 'images/ring14.jpeg', 'A fresh spin on the traditional diamond ring. A bevy of dazzling zircons surround a radiant centrepiece, creating a truly enchanting atmosphere.<br> All of this is set on a revolving base, giving this Rose Gold Solitaire Spin Ring ring a truly modern twist', 'AAA+ Quality Zircon Stones. <br>\r\n925 Sterling Silver with Rose Gold plating.<br>\r\nAdjustable size to ensure no fitting issues.<br>\r\nRing size 8-10/ 18mm -19.8mm (adjustable).', NULL),
(31, 'Rose Gold Floral Chic Ring', 'Ring', 'Rs 1399', 'images/ring15.jpeg', 'The Rose Gold Floral Glory Ring has a lovely floral design with studded zircons.', 'Deck up in a Hot pink one-shoulder gown and pair it up with this ring.', '925 Sterling Silver with Rose Gold plating.<br>\r\nAdjustable size to ensure no fitting issues.<br>\r\nAAA+ Quality Zircons.<br>\r\nDiameter: 18mm + top Adjustable.<br> \r\nDimension: 12 x 7.5 mm.'),
(32, 'Silver Linked Heart Ring', 'Ring', 'Rs 1599', 'images/ring16.jpeg', 'We’re all looking for The One, but only a fortunate few ever find their match.<br> This Silver Linked Heart Ring is for YOU lucky ones - two beautiful and dazzling spirits coming together to create something magical.<br> And if YOU haven’t found YOURS yet, maybe this is the lucky charm YOU need?', 'This Silver Linked Heart Ring is handcrafted with love, just for YOU!<br> An intricately crafted beauty, this ring features two gorgeous hearts coming together in the truest sense.<br> Entirely crafted in sterling silver, for that little touch of class.', 'This ring is ready to conquer YOUR heart. So flaunt it wherever YOU go!\r\n<br><br>\r\nAAA+ Quality Zircon Stones.<br>\r\n925 Sterling Silver.<br>\r\nAdjustable size to ensure no fitting issues.<br>\r\nRing size 5.5-10/ 16mm -19.8mm (adjustable).<br>\r\nRhodium e-coat to prevent tarnish.'),
(33, 'Rose Gold Drop Wreath Pendant Set', 'Set', 'Rs 2899', 'images/set1.jpeg', 'The Rose Gold Pink Drop Wreath Pendant Set is inspired by the most special moments of life that make it all worth it.', 'The Rose Gold Pink Drop Wreath Pendant Set is handcrafted with love, just for YOU.<br> These intricately made studs possess all the thoughtfulness you need around you.<br> With the perfect balance of leaves, flowers, and drop design, this set is nothing less than a true masterpiece.\r\n', 'Take this set along for those special, close-to-heart moments.\r\n<br><br>\r\nIncludes the Rose Gold Pink Drop Wreath Studs and Rose Gold Pink Drop Wreath Pendant.<br>\r\n16\" + 2\" adjustable Rose Gold Chain.<br>\r\nCharm - 21mm X 15mm, Dimensions - 12mm X 13mm.<br>\r\n925 Silver with Rose Gold Plating.<br>\r\nAAA+ Quality Zircons.<br>\r\nHypoallergenic - Perfect for sensitive skin.'),
(34, 'Golden Princess Set', 'Set', 'Rs 4099', 'images/set2.jpeg', 'The Golden Princess Set is inspired by the one who knows her time to shine has come.\r\n', 'This set has an eye-catching elongated hoop with a cluster of zircons on the top and the bottom tip.', '925 Silver with Gold Plating.<br>\r\nPerfect for sensitive skin.<br>\r\nEarring Height: 4 cm, Width: 1.8 cm.<br> \r\nMotif Height: 3.6 cm, Motif Width: 1.6 cm.<br>\r\nThe necklace size is 43 cm and the adjustable chain is 4 cm.'),
(35, 'Silver Deer Solitaire Heart Set', 'Set', 'Rs 2999', 'images/set3.jpeg', 'The Silver Deer Solitaire Heart Set is inspired by the innocent heart of a deer.', 'The Silver Set includes a necklace with a charm shaped like a deer with solitaire heart earrings.', '925 Silver.<br> \r\nNecklace Charm Dimensions - 2.2 cm X 2.4 cm.<br>\r\nThe length of the necklace is 38 cm with a 5 cm adjustable portion.<br>\r\nEarrings Dimensions: 0.15 cm X 0.15 cm.<br>\r\nHypoallergenic - Perfect for sensitive skin.'),
(36, 'Golden Zircon Set', 'Set', 'Rs 3099', 'images/set4.jpeg', 'Golden Zircon set with pendant and earrings holds a special place in my heart and mind. Simple, and stunning!\r\n', 'This set has a pendant and a pair of earrings in sparkling zircon and features the most gorgeous sparkling crystal.', '925 Silver with Gold Plating.<br>\r\nPerfect for sensitive skin.<br>\r\nEarring Height: 0.7 cm, Width: 0.7 cm.<br> \r\nMotif Height: 1.7 cm, Motif Width: 0.8 cm.<br>\r\nThe necklace size is 42 cm and the adjustable chain is 4 cm.'),
(37, 'Silver Leaf Set', 'Set', 'Rs 3099', 'images/set5.jpeg', 'The Silver Leaf Set is inspired by the morning view of leaves painted with the dew glass. ', 'The Silver Leaf Set has a silver studded leaf pattern necklace and a pair of leaf earrings. ', 'Includes the Silver Leaf Necklace and Silver Leaf Earrings.<br>\r\n925 Silver.<br>\r\nAAA+ Quality Zircons.<br>\r\nNecklace Length: 16 inch+2 inch Adjustable.<br> Charm: 31 mm x 8 mm.<br>\r\nEarrings Dimension: 6 mm x 15 mm.<br> \r\nRhodium finish to prevent tarnish.'),
(38, 'Rose Gold Sugar Crystal Set', 'Set', 'Rs 3299', 'images/set6.jpeg', 'The Rose Gold Sugar Crystal Set is inspired by the versatility of baguettes because no matter what the occasion, what the time, they never go wrong.', 'Rose Gold Sugar Crystal Set has a pair of earrings and a necklace that has a classic Baguette shape.<br> The shiniest zircons surround the design and the rose gold plating is the cherry on top.', 'Includes 16\" + 2\" adjustable Rose Gold Chain.<br>\r\n925 Sterling Silver and Rose Gold plating.<br>\r\nAAA+ Quality Zircon Stones.<br>\r\nHypoallergenic - Perfect for sensitive skin.'),
(39, 'Rose Gold Tree of Life Set', 'Set', 'Rs 3399', 'images/set7.jpeg', 'The tree of life represents progress and strength. <br>The trunk and branches depict life\'s myriad paths , while the dazzling gems symbolize the hearts you cherish the most.<br> This isn\'t just jewellery, it\'s an ode to your growth through this journey of life.', 'High quality zircon stones.<br>\r\n16\"+2.5\" silver chain.<br>\r\nSterling silver base.<br>\r\n925 silver jewellery.', NULL),
(40, 'Moonlight Pearl Set', 'Set', 'Rs 2299', 'images/set8.jpeg', 'Bask in the luminescence of the moon with this enchanting combination from GIVA.<br> This timeless set exudes class, making it hard not to fall in love.', 'Includes Pearl Moon Pendant + Pearl Earrings.<br>\r\nSterling silver base.<br>\r\nFreshwater pearl  with lacquer coating.<br>\r\nAnti-tarnish rhodium e-coat to prevent silver tarnish.', NULL),
(41, 'Silver Love Like A Butterfly Set', 'Set', 'Rs 2599', 'images/set9.jpeg', 'The Silver Love Like A Butterfly Set is inspired by the fluttering feelings that make you flash a radiant smile every time you look at the love of your life!\r\n', 'The Silver Love Like A Butterfly Set has a unique butterfly design with a centrepiece studded with gorgeous zircons.', 'Includes the Silver Love Like A Butterfly Pendant and pair of Silver Love Like A Butterfly Studs.<br>\r\n925 Sterling silver.<br>\r\nAAA+ Quality Zircons.<br>\r\nEarrings Dimension: 12 mm x 8.5 mm.<br>\r\nPendant Charm: 22.5 mm x 14 mm.<br>\r\nAnti-tarnish rhodium finish to prevent tarnish.'),
(42, 'Rose Gold Floral Set', 'Set', 'Rs 4099', 'images/set10.jpeg', 'The Rose Gold Floral Set is inspired by the blooming sparkle found in a paradise - one filled with pixies and fairies!\r\n\r\n', 'The Rose Gold Floral Set is a beautiful design of a gorgeous flower, studded with zircons and a Rose Gold finish.', 'Includes the Rose Gold Floral Pendant With Link Chain and Rose Gold Meandering Heart Studs.<br>\r\nAAA+ Quality Zircons.<br>\r\nNecklace Chain Length: 40 cm+ 4 cm.<br> Adjustable; Charm: 29 mm x 13 mm.<br>\r\nEarrings Dimension: 17 mm x 9 mm.<br>\r\nHypoallergenic - Perfect for sensitive skin.<br>\r\n925 Silver with Rose Gold plating.'),
(43, 'Rose Gold Flower Basket Set', 'Set', 'Rs 3699', 'images/set11.jpeg', 'The Rose Gold Flower Basket Set is inspired by the beautiful arrangement of flowers that create harmony between various plant families. ', 'The Rose Gold Set has a necklace with a horizontal rose in the centre and a pair of earrings shaped like a wreath.', '925 Silver.<br>\r\nAAA+ Quality Zircons.<br>\r\nAdjustable size to ensure no fitting issues.<br>\r\nDimensions of earrings are 1.2 cm X 1.3 cm.<br>\r\nLength: 17\" + Adjustable.'),
(44, 'French Rose Set', 'Set', 'Rs 12999', 'images/set12.jpeg', 'The French Rose Set is inspired by misty mornings imbued with the refreshing scents of blooming roses! <br>The subtle notes of revitalizing blossoms that make you want to ponder over soothing thoughts and root for what you own as inevitably yours!', 'This silver necklace and earrings set has an alternate placement of dazzling zircons amidst the coloured stones giving it an ethereal look.', '925 Silver with Rose Gold Plating.<br>\r\nPerfect for sensitive skin.<br>\r\nEarring Height: 3 cm, Width: 1 cm.<br>\r\nThe necklace size is 43 cm and the adjustable chain is 5 cm.'),
(45, 'Silver Queens Set', 'Set', 'Rs 2899', 'images/set13.jpeg', 'Silver Queens Set is inspired by the cottagecore aesthetic with minimal and cute jewellery pieces that is romantic. ', 'The silver set has a necklace with drops of crystal on a dainty silver chain to add sparkle to your look and a pair of earrings that feature the most gorgeous sparkling crystals, set in a square of silver. ', '925 Fine Silver.<br>\r\nAAA+ Quality Zircon Stones.<br>\r\nContains a necklace and a pair of earrings.<br>\r\nNecklace length is 40 cm with 5 cm adjustable portion.<br>\r\nEarring Charm: 0.8 mm X 0.8 mm.<br>\r\nRhodium finish to prevent tarnish.'),
(46, 'Golden Forever In Blue Set', 'Set', 'Rs 4599', 'images/set14.jpeg', 'The Golden Forever In Blue Set is inspired by the true-blue feeling of never having to let go of each other and making your dream of an epic love story come true!\r\n', 'The Golden Forever In Blue Set has a concentric shape design with a blue coloured stone in the centre and a zircon studded floral charm on top, the same design seen on both the pendant charm and earrings.', 'Includes the Golden Forever In Blue Pendant with Link Chain and a pair of Golden Forever In Blue Earrings.<br>\r\n925 Silver with Gold Plating.<br>\r\nPendant Charm: 30.2 mm x 16.4 mm.<br>\r\nEarrings Charm: 21.4 mm x 11.8 mm.'),
(47, 'Silver Pink Flower Drop Solitaire Set', 'Set', 'Rs 8399', 'images/set15.jpeg', 'Flowers & diamonds, a DIVA’s two best friends which never let her down no matter what.<br> Capturing the beauty of this eternal & shiny bond with this Silver Pink Flower Drop Solitaire Set.', 'Silver Pink Flower Drop Solitaire Set is handcrafted with love, just for YOU.<br> The pink flowers are made complete with the pop drop surrounded by the shiniest zircons- a complete package.', 'We bet this’ll match YOUR perfect party dress!\r\n<br><br>\r\nIncludes the Silver Pink Flower Drop.<br> Solitaire Pendant, a 16\" + 2\" adjustable Silver Chain, and a pair of Silver Pink Flower Drop Solitaire Earrings.<br>\r\n925 Sterling Silver.<br>\r\nAAA+ Quality Zircons.<br>\r\nHypoallergenic - Perfect for sensitive skin.<br>\r\nRhodium e-coat to prevent tarnish.'),
(48, 'Golden Zircon Studded Heart Set', 'Set', 'Rs 3299', 'images/set16.jpeg', 'The Golden 3D Zircon Studded Heart set is inspired by the idea of the spark when two hearts merge into one.', 'The Golden 3D heart set is embedded with a prominent zircon stone.', '925 Silver with Gold plating.<br>\r\nIncludes a ring and a pendant with a link chain.<br>\r\nHypoallergenic - Perfect for sensitive skin.<br>\r\nRing diameter: 1.7 cm +adjustable.<br> \r\nPendant Dimensions: 1.94 cm x 1.49 cm.'),
(49, 'Silver Love Like A Butterfly Studs', 'Earing', 'Rs 999', 'images/earing1.jpeg', 'The Silver Love Like A Butterfly Studs are inspired by the fluttering feelings that make you flash a radiant smile every time you look at the love of your life!', 'The Silver Love Like A Butterfly Studs have a unique butterfly design with a centrepiece studded with gorgeous zircons.', 'AAA+ Quality Zircons.<br>\r\nDimensions: 12 mm x 8.5 mm.<br> \r\n925 Sterling silver.<br> \r\nHypoallergenic - Perfect for sensitive ears.<br>\r\nRhodium finish to prevent tarnish.'),
(50, 'Rose Gold Drop Wreath Studs', 'Earing', 'Rs 1499', 'images/earing2.jpeg', 'These Rose Gold Drop Wreath Studs are inspired by the most special moments of life that make it all worth it.', 'These Rose Gold Drop Wreath Studs are handcrafted with love, just for YOU.<br> These intricately made studs possess all the thoughtfulness you need around you.<br> With the perfect balance of leaves, flowers, and drop design, these studs are nothing less than a true masterpiece.', 'Take these along for those special, close-to-heart moments.\r\n<br><br>\r\nDimensions - 12mm X 13mm.<br>\r\nAAA+ Quality Zircons.<br>\r\nHypoallergenic - Perfect for sensitive skin.'),
(51, 'Rose Gold Zircon Drizzle Drop Earrings', 'Earing', 'Rs 1699', 'images/earing3.jpeg', 'The Rose Gold Drizzle Drop Earrings are inspired by the sparkling drops of rain that wash away our doubts and fears with resilience and determination.', 'These rose gold earrings feature large zircons set at the centre, adorned with small ones studded around the motif that dangle from zircon studded hoops.', '925 Silver with Rose Gold Plating.<br>\r\nPerfect for sensitive skin.<br>\r\nSize: Height - 2.6 cm Width - 0.95 cm.'),
(52, 'Golden Princess Earrings', 'Earing', 'Rs 1699', 'images/earing4.jpeg', 'The Golden Princess Earrings are inspired by the one who knows her time to shine has come.\r\n', 'These earrings have an eye-catching elongated hoop with a cluster of zircons on the top and the bottom tip.', '925 Silver with Gold Plating.<br>\r\nPerfect for sensitive skin.<br>\r\nSize: Height - 3.6 cm, Width - 1.6 cm.'),
(53, 'Golden Butterfly Studded Affair Earrings', 'Earing', 'Rs 99', 'images/earing5.jpeg', 'The Golden Butterfly Studded Affair Earrings are inspired by the elegant fluttering of the wings that characterizes the flight of these butterflies.\r\n', 'The Golden Butterfly Studded Affair Earrings are handcrafted with love only for YOU!<br> The seamless shape of a soaring butterfly with the added sparkle of zircons makes these earrings befitting for YOU!', 'Dimensions - 5mm X 6mm.<br>\r\nAAA+ Quality Zircon Stones.<br>\r\nPerfect for sensitive ears.'),
(54, 'Silver Zircon Drizzle Drop Earring', 'Earing', 'Rs 1499', 'images/earing6.jpeg', 'Like a light drizzle on a summer afternoon, YOU are a marvel of nature that leaves everyone spellbound.<br> But even a soothing drizzle feels better when it partners with a chilly breeze. ', 'Presenting the Silver Zircon Drizzle Drop Earrings, the breeze to your drizzle.', 'AAA+ Quality Zircons.<br>\r\n925 Sterling silver.<br>\r\nPerfect for sensitive ears.<br>\r\nRhodium e-coat to prevent tarnish.'),
(55, 'Rose Gold Princess Earrings', 'Earing', 'Rs 1699', 'images/earing7.jpeg', 'Feel like a princess with these rose gold dangling earrings. An eye catchy piece with cluster of zircons at the top & the bottom tip.', '925 Silver with Rose Gold plating.<br>\r\nAAA+ quality Zircon.', NULL),
(56, 'Golden Zircon Earrings', 'Earing', 'Rs 1499', 'images/earing8.jpeg', 'These Golden Zircon Earrings holds a special place in our hearts. Simple, and stunning!', 'These earrings in sparkling zircon feature the most gorgeous sparkling crystal.', '925 Silver with Gold Plating.<br>\r\nPerfect for sensitive skin.<br>\r\nSize: Height - 0.7 cm, Width - 0.7 cm.'),
(57, 'Silver Small Heart Drop Earring', 'Earing', 'Rs 999', 'images/earing9.jpeg', 'Dil hai chhota sa, chhoti si asha. We heard you, we know you want these cuties so we\'ll keep it short. Utterly charming, unbelievably adorable, Silver Small Heart Drop Earrings.', '925 Sterling Silver.<br>\r\nPerfect for sensitive ears.<br>\r\nRhodium e-coat to prevent tarnish.', NULL),
(58, 'Golden Blooming Flower Stud Earrings', 'Earing', 'Rs 1499', 'images/earing10.jpeg', 'DIVA, there are few things as beautiful as nature in all its glory.<br> And what better to represent the charm of nature than a flower in full bloom! <br>Inspired by nature at its finest, these Golden Blooming Flower Studs are our attempt at capturing nature\'s magic.', 'These Golden Blooming Flower Studs have been handcrafted especially for YOU! <br>These earrings have been intricately designed to match nature’s peerless brilliance.<br> Zircon studded gold has been delicately crafted to represent a flower in full bloom, capturing the true essence of nature.', 'These adorable earrings are truly enchanting! Work or party, they\'ll never let YOU down.\r\n<br><br>\r\nAAA+ Quality Zircon Stones.<br>\r\n925 Sterling Silver with Gold plating.<br> \r\nPerfect for sensitive ears.'),
(59, 'Silver Zircon Small Heart Studs', 'Earing', 'Rs 1099', 'images/earing11.jpeg', 'For the DIVA who believes less is more, we present these dainty Small Heart Studs. The epitome of minimal size, maximum impact.', 'AAA+ Quality Zircons.<br>\r\n925 Sterling silver.<br> \r\nPerfect for sensitive ears.<br>\r\nRhodium e-coat to prevent tarnish.', NULL),
(60, 'Silver Royal Blue Bloom Studs', 'Earing', 'Rs 1099', 'images/earing12.jpeg', 'Silver Royal Blue Bloom Studs are truly inspired by the royalty and the regal bloom that follows. A perfect pick for our queen DIVAs.', 'Silver Royal Blue Bloom Studs are handcrafted with love, just for YOU.<br> These studs are as royal as the name itself.<br> Blooming with the regal vibes, this is a perfect option for the DIVAs who are no less than queens.', 'Reign with these beauties, rule the world.\r\n<br><br>\r\nAAA+ Quality Zircons.<br>\r\nDimensions - 9mm X 9mm.<br>\r\nHypoallergenic - Perfect for sensitive ears.<br>\r\nRhodium e-coat to prevent tarnish.'),
(61, 'Silver Pearl Small Stud Earrings', 'Earing', 'Rs 1099', 'images/earing13.jpeg', 'A fresh pearl, right out of the oyster, is the purest of them all.<br> We wanted to bring our DIVAs nothing less than perfect.<br> So we settled for the purest form – These Silver Pearl Small Stud Earrings.', 'These Silver Pearl Small Stud Earrings are handcrafted with love, just for YOU!<br> Though simple, the earrings are the epitome of grace and charm.<br> An elegant pearl nestles in a curved Silver body, ready to embrace your ears!', 'Once on, YOU wouldn’t want to take them off, we promise!\r\n<br><br>\r\n5mm Freshwater Pearls.<br>\r\n925 Sterling Silver.<br> \r\nRhodium e-coated to prevent tarnish.'),
(62, 'Golden Star Constellation Studs', 'Earing', 'Rs 999', 'images/earing14.jpeg', 'DIVA, YOU are a beauty from the heavens. An angel living amongst the stars, YOU descended to make our world a better place.<br> Inspired by YOUR old friends, the little celestials that light up our night sky, comes this Golden Star Constellation Studs.', 'This Golden Star Constellation Studs are handcrafted with love, especially for YOU.<br> With intricately arranged stars on a golden chain, this sparkling studs are reminiscent of YOUR favourite celestial body.', 'These studs are here to make YOU stand out! Wear them whenever YOU want that extra oomph.\r\n<br><br>\r\nAAA+ Quality Zircon Stones.<br>\r\n925 Sterling Silver with Gold plating.<br>\r\nPerfect for sensitive ears.'),
(63, 'Rose Gold Made for Each Other Stud Earrings', 'Earing', 'Rs 999', 'images/earing15.jpeg', 'The Rose Gold Made for Each Other Stud Earrings are inspired by the perfect love story, one where both partners have equal shares of love and commitment.\r\n', 'The Rose Gold Made for Each Other Studs has a very thoughtful design of a heart with one half studded with zircons and the other half of the heart with a rose gold coating.', 'Perfect for sensitive ears.<br>\r\nAAA+ Quality Zircons.<br>\r\nCharm: 12 mm x 9 mm.'),
(64, 'Rose Gold Crescent Affair Earring', 'Earing', 'Rs 1799', 'images/earing16.jpeg', 'An illuminating zircon studded fine design for you. Elaborate piece yet light weight to enhance your elegant side.', 'Rose Gold plating.<br>\r\nAAA+ quality Zircon.<br>\r\nSterling silver base.', NULL);

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `First_Name` varchar(25) NOT NULL,
  `Last_Name` varchar(25) NOT NULL,
  `Email` varchar(50) NOT NULL,
  `Password` varchar(20) NOT NULL,
  `Phone_No` bigint(10) UNSIGNED NOT NULL,
  `Address_Line_1` varchar(50) DEFAULT NULL,
  `Address_Line_2` varchar(50) DEFAULT NULL,
  `Address_Line_3` varchar(50) DEFAULT NULL,
  `Pincode` int(6) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`First_Name`, `Last_Name`, `Email`, `Password`, `Phone_No`, `Address_Line_1`, `Address_Line_2`, `Address_Line_3`, `Pincode`) VALUES
('Goldi', 'Barai', 'goldi0108@gmail.com', 'ILS', 8779820636, 'B-1202,Ansuman Apartment', 'Antophill,Wadala', 'Near Antophill Bus Station, Mumbai', 400037),
('Krish', 'Jain', 'krishjain1903@gmail.com', 'ILMS', 9987313390, 'B-202, Shree Durga Complex Chs', 'Plot No:-4, Sec:-3,Ghansoli, Navi Mumbai', 'Near Ghansoli Railway Station', 400701),
('Usha', 'Jain', 'ushajain779@gmail.com', 'USHA', 9702779899, 'Room No:-7,Hemal Bldg', 'Road No:-16, Wagle Estate, Thane', '', 400604);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`Id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`Email`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
